import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/_common/styles/globals.css'
import Header from './_components/layouts/header'
import Footer from './_components/layouts/footer'
import NextAuthProvider from './_features/auth/providers/NextAuth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <NextAuthProvider>
          <div className="text-black-333">
            <Header />
            <main>{children}</main>
            <Footer />
          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
