import type { Metadata } from 'next'
import { Inter, Noto_Sans_JP } from 'next/font/google'
import '@/app/_common/styles/globals.css'
import Header from './_components/layouts/header'
import Footer from './_components/layouts/footer'
import NextAuthProvider from './_features/auth/providers/NextAuth'
import BottomNavigation from './_components/layouts/bottomNavigation'

const inter = Inter({ subsets: ['latin'] })
const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={`${notoSansJP.className}`}>
        <NextAuthProvider>
          <div className="text-color-main-800">
            <Header />
            <main>{children}</main>
            <BottomNavigation />
            <Footer />
          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
